#!/bin/sh
#
#  hgrepo-setupserver -- part of hg-helpers.
#
#  Must be executed on server side before any other hgrepo-xx command.
#

GROUP="repousers"
UBASE="/home/repousers"
RBASE="/home/repos"

F="/etc/ssh/sshd_config"

echo "Step 1/3. Install packages..."
apt-get install -y mercurial openssh-server sudo

echo "Step 2/3. Configure Secure Shell server..."

SSH_GROUPS="$(EDITOR=cat visudo | egrep '^%.*=.*ALL$' | sed -e 's,^%,, ; s,\s.*,,' | xargs echo)"
echo "SSH access will allowed only for groups: $SSH_GROUPS $GROUP"
need_restart=

cfgline() {
	#echo "Check $F for $*..."
	grep -q -- "^$*" "$F" && return
	need_restart=1
	echo "Added to $F: $*"
	echo "$*" >> "$F"
}

cfgline "UseDNS no"
cfgline "AllowGroups $SSH_GROUPS $GROUP"
cfgline "AllowAgentForwarding no"
cfgline "AllowTcpForwarding no"
cfgline "X11Forwarding no"

test -n "$need_restart" && service ssh restart

echo "Step 3/3. Create groups and directories..."

groupadd "$GROUP"

mkdir -pm750 "$RBASE"; chgrp "$GROUP" "$RBASE"
mkdir -pm710 "$UBASE"; chgrp "$GROUP" "$UBASE"

echo "Done."

## EOF ##
